---
- name: ansible test playbook
  hosts: all
  gather_facts: false
  vars:
    path: /home/ansible
    filename: services.txt
    services:
      - apache2
      - nginx
  tasks:
  - name: write the service list into file
    lineinfile:
      path: "{{path}}/{{filename}}"
      line: "{{services}}"
      create: yes
...
